server:
  port: 8081

spring:
  application:
    name: market-service
  datasource:
    url: jdbc:mysql://localhost:3307/market_db
    username: root
    password: 305656
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
server:
  port: 8082

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3308/customer_db
    username: root
    password: 305656
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect